mongo AnnotationSource chr1.js  > chr1.json
mongo AnnotationSource chr2.js  > chr2.json
mongo AnnotationSource chr3.js  > chr3.json
mongo AnnotationSource chr4.js  > chr4.json
mongo AnnotationSource chr5.js  > chr5.json
mongo AnnotationSource chr6.js  > chr6.json
mongo AnnotationSource chr7.js  > chr7.json
mongo AnnotationSource chr8.js  > chr8.json
mongo AnnotationSource chr9.js  > chr9.json
mongo AnnotationSource chr10.js  > chr10.json
mongo AnnotationSource chr11.js  > chr11.json
mongo AnnotationSource chr12.js  > chr12.json
mongo AnnotationSource chr13.js  > chr13.json
mongo AnnotationSource chr14.js  > chr14.json
mongo AnnotationSource chr15.js  > chr15.json
mongo AnnotationSource chr16.js  > chr16.json
mongo AnnotationSource chr17.js  > chr17.json
mongo AnnotationSource chr18.js  > chr18.json
mongo AnnotationSource chr19.js  > chr19.json
mongo AnnotationSource chr20.js  > chr20.json
mongo AnnotationSource chr21.js  > chr21.json
mongo AnnotationSource chr22.js  > chr22.json
mongo AnnotationSource chrX.js  > chrX.json
mongo AnnotationSource chrY.js  > chrY.json
