grep -E 	'^chr1\s'	canonical_transcripts_ensembl_20160204.plusENSEMBLdiff.includealtrandom.aggregate.scores.txt	> 	chr1.originalScore
grep -E 	'^chr2\s'	canonical_transcripts_ensembl_20160204.plusENSEMBLdiff.includealtrandom.aggregate.scores.txt	> 	chr2.originalScore
grep -E 	'^chr3'	canonical_transcripts_ensembl_20160204.plusENSEMBLdiff.includealtrandom.aggregate.scores.txt	> 	chr3.originalScore
grep -E 	'^chr4'	canonical_transcripts_ensembl_20160204.plusENSEMBLdiff.includealtrandom.aggregate.scores.txt	> 	chr4.originalScore
grep -E 	'^chr5'	canonical_transcripts_ensembl_20160204.plusENSEMBLdiff.includealtrandom.aggregate.scores.txt	> 	chr5.originalScore
grep -E 	'^chr6'	canonical_transcripts_ensembl_20160204.plusENSEMBLdiff.includealtrandom.aggregate.scores.txt	> 	chr6.originalScore
grep -E 	'^chr7'	canonical_transcripts_ensembl_20160204.plusENSEMBLdiff.includealtrandom.aggregate.scores.txt	> 	chr7.originalScore
grep -E 	'^chr8'	canonical_transcripts_ensembl_20160204.plusENSEMBLdiff.includealtrandom.aggregate.scores.txt	> 	chr8.originalScore
grep -E 	'^chr9'	canonical_transcripts_ensembl_20160204.plusENSEMBLdiff.includealtrandom.aggregate.scores.txt	> 	chr9.originalScore
grep -E 	'^chr10'	canonical_transcripts_ensembl_20160204.plusENSEMBLdiff.includealtrandom.aggregate.scores.txt	> 	chr10.originalScore
grep -E 	'^chr11'	canonical_transcripts_ensembl_20160204.plusENSEMBLdiff.includealtrandom.aggregate.scores.txt	> 	chr11.originalScore
grep -E 	'^chr12'	canonical_transcripts_ensembl_20160204.plusENSEMBLdiff.includealtrandom.aggregate.scores.txt	> 	chr12.originalScore
grep -E 	'^chr13'	canonical_transcripts_ensembl_20160204.plusENSEMBLdiff.includealtrandom.aggregate.scores.txt	> 	chr13.originalScore
grep -E 	'^chr14'	canonical_transcripts_ensembl_20160204.plusENSEMBLdiff.includealtrandom.aggregate.scores.txt	> 	chr14.originalScore
grep -E 	'^chr15'	canonical_transcripts_ensembl_20160204.plusENSEMBLdiff.includealtrandom.aggregate.scores.txt	> 	chr15.originalScore
grep -E 	'^chr16'	canonical_transcripts_ensembl_20160204.plusENSEMBLdiff.includealtrandom.aggregate.scores.txt	> 	chr16.originalScore
grep -E 	'^chr17'	canonical_transcripts_ensembl_20160204.plusENSEMBLdiff.includealtrandom.aggregate.scores.txt	> 	chr17.originalScore
grep -E 	'^chr18'	canonical_transcripts_ensembl_20160204.plusENSEMBLdiff.includealtrandom.aggregate.scores.txt	> 	chr18.originalScore
grep -E 	'^chr19'	canonical_transcripts_ensembl_20160204.plusENSEMBLdiff.includealtrandom.aggregate.scores.txt	> 	chr19.originalScore
grep -E 	'^chr20'	canonical_transcripts_ensembl_20160204.plusENSEMBLdiff.includealtrandom.aggregate.scores.txt	> 	chr20.originalScore
grep -E 	'^chr21'	canonical_transcripts_ensembl_20160204.plusENSEMBLdiff.includealtrandom.aggregate.scores.txt	> 	chr21.originalScore
grep -E 	'^chr22'	canonical_transcripts_ensembl_20160204.plusENSEMBLdiff.includealtrandom.aggregate.scores.txt	> 	chr22.originalScore
grep -E 	'^chrX'	canonical_transcripts_ensembl_20160204.plusENSEMBLdiff.includealtrandom.aggregate.scores.txt	> 	chrX.originalScore
grep -E 	'^chrY'	canonical_transcripts_ensembl_20160204.plusENSEMBLdiff.includealtrandom.aggregate.scores.txt	> 	chrY.originalScore
