grep -E 	'^chr1\s|chr1_'	refseq_canonical_transcripts_20160203.includealtrandom.aggregate.scores.txt	> 	chr1.originalScore
grep -E 	'^chr2\s|chr2_'	refseq_canonical_transcripts_20160203.includealtrandom.aggregate.scores.txt	> 	chr2.originalScore
grep -E 	'^chr3'	refseq_canonical_transcripts_20160203.includealtrandom.aggregate.scores.txt	> 	chr3.originalScore
grep -E 	'^chr4'	refseq_canonical_transcripts_20160203.includealtrandom.aggregate.scores.txt	> 	chr4.originalScore
grep -E 	'^chr5'	refseq_canonical_transcripts_20160203.includealtrandom.aggregate.scores.txt	> 	chr5.originalScore
grep -E 	'^chr6'	refseq_canonical_transcripts_20160203.includealtrandom.aggregate.scores.txt	> 	chr6.originalScore
grep -E 	'^chr7'	refseq_canonical_transcripts_20160203.includealtrandom.aggregate.scores.txt	> 	chr7.originalScore
grep -E 	'^chr8'	refseq_canonical_transcripts_20160203.includealtrandom.aggregate.scores.txt	> 	chr8.originalScore
grep -E 	'^chr9'	refseq_canonical_transcripts_20160203.includealtrandom.aggregate.scores.txt	> 	chr9.originalScore
grep -E 	'^chr10'	refseq_canonical_transcripts_20160203.includealtrandom.aggregate.scores.txt	> 	chr10.originalScore
grep -E 	'^chr11'	refseq_canonical_transcripts_20160203.includealtrandom.aggregate.scores.txt	> 	chr11.originalScore
grep -E 	'^chr12'	refseq_canonical_transcripts_20160203.includealtrandom.aggregate.scores.txt	> 	chr12.originalScore
grep -E 	'^chr13'	refseq_canonical_transcripts_20160203.includealtrandom.aggregate.scores.txt	> 	chr13.originalScore
grep -E 	'^chr14'	refseq_canonical_transcripts_20160203.includealtrandom.aggregate.scores.txt	> 	chr14.originalScore
grep -E 	'^chr15'	refseq_canonical_transcripts_20160203.includealtrandom.aggregate.scores.txt	> 	chr15.originalScore
grep -E 	'^chr16'	refseq_canonical_transcripts_20160203.includealtrandom.aggregate.scores.txt	> 	chr16.originalScore
grep -E 	'^chr17'	refseq_canonical_transcripts_20160203.includealtrandom.aggregate.scores.txt	> 	chr17.originalScore
grep -E 	'^chr18'	refseq_canonical_transcripts_20160203.includealtrandom.aggregate.scores.txt	> 	chr18.originalScore
grep -E 	'^chr19'	refseq_canonical_transcripts_20160203.includealtrandom.aggregate.scores.txt	> 	chr19.originalScore
grep -E 	'^chr20'	refseq_canonical_transcripts_20160203.includealtrandom.aggregate.scores.txt	> 	chr20.originalScore
grep -E 	'^chr21'	refseq_canonical_transcripts_20160203.includealtrandom.aggregate.scores.txt	> 	chr21.originalScore
grep -E 	'^chr22'	refseq_canonical_transcripts_20160203.includealtrandom.aggregate.scores.txt	> 	chr22.originalScore
grep -E 	'^chrX'	refseq_canonical_transcripts_20160203.includealtrandom.aggregate.scores.txt	> 	chrX.originalScore
grep -E 	'^chrY'	refseq_canonical_transcripts_20160203.includealtrandom.aggregate.scores.txt	> 	chrY.originalScore
